# fly.toml app configuration file generated for myapp-wild-feather-9430 on 2024-08-11T09:30:52+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'myapp-wild-feather-9430'
primary_region = 'cdg'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 6
  processes = ['app']

[[vm]]
  size = 'performance-16x'
